"""
Import coordinator for external creative tools.

External systems only need to provide extracted story/script/storyboard text.
This module coordinates a small set of layer agents that convert the source
material into pm-mem Markdown memory layers.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from local_llm_client import (
    DeepSeekChatLLMClient,
    ImportLLMSettings,
    LocalResponsesLLMClient,
    load_import_llm_settings,
)
import memory_manager
import role_manager
from src.agent.remem_agent import ReMemAgent
from src.agent.roles import RoleFactory
from src.memory.schema import TaskContext
from src.memory.stores import MarkdownLayerMemoryStore, MarkdownTraceStore


DEFAULT_SOURCE_SYSTEM = "外部创作系统"


@dataclass
class ExternalWorkPayload:
    """Normalized source material from an external creative system."""

    source_system: str
    external_work_id: str
    work_name: str
    source_url: str = ""
    story: str = ""
    script: str = ""
    storyboard_script: str = ""
    images: List[str] = field(default_factory=list)
    raw_payload: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LayerDraft:
    """One memory layer generated by one import agent."""

    layer_id: str
    agent_name: str
    content: str
    role_id: str = ""
    role_name: str = ""
    role_file: str = ""
    role_prompt: str = ""
    role_prompt_hash: str = ""
    llm_provider: str = ""
    llm_processed: bool = False
    llm_model: str = ""
    llm_endpoint: str = ""
    llm_primary_error: str = ""
    llm_error: str = ""
    notes: List[str] = field(default_factory=list)


class ImportLayerAgent:
    """Base class for deterministic layer agents."""

    layer_id = ""
    agent_name = ""
    role_id = ""

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        raise NotImplementedError

    def _empty_hint(self, label: str) -> str:
        return f"（外部系统未提供{label}，待人工审核补充。）"

    def _section(self, title: str, content: str, empty_label: Optional[str] = None) -> str:
        body = (
            content.strip()
            if content and content.strip()
            else self._empty_hint(empty_label or title)
        )
        return f"## {title}\n\n{body}"

    def _draft(self, content: str, notes: Optional[List[str]] = None) -> LayerDraft:
        return LayerDraft(
            self.layer_id,
            self.agent_name,
            content,
            role_id=self.role_id,
            notes=notes or [],
        )

    def build_llm_prompt(
        self,
        payload: ExternalWorkPayload,
        draft: LayerDraft,
        role_prompt: str,
        previous_drafts: Dict[str, LayerDraft],
    ) -> str:
        layer_name = memory_manager.get_layer_definition(self.layer_id)["layer_name"]
        previous_summary = _summarize_previous_drafts(previous_drafts)
        return f"""# 角色 Prompt
{role_prompt or "（未配置角色 prompt，请按目标层规则处理。）"}

# 任务
你正在把外部作品导入 pm-mem Markdown 分层记忆。请以当前角色身份处理并提炼要写入「{layer_name}」的内容。

# 输出要求
- 只输出可以直接写入该记忆层的 Markdown 正文，不要输出代码块。
- 保留外部素材中的事实，不要编造未出现的人物、关系、时间线或场景。
- 不确定的信息标注为“待人工确认”。
- 归档层需要保留原文或原始结构，不要为了摘要而丢失可复查内容。
- 内容应可供后续编剧、分镜师、制片人继续读取和维护。

# 作品信息
作品名称：{payload.work_name}
来源系统：{payload.source_system}
外部作品 ID：{payload.external_work_id}
来源 URL：{payload.source_url or "未提供"}

# 已生成的前置记忆层
{previous_summary or "（暂无前置层。）"}

# 当前确定性草稿
{draft.content}

# 外部故事
{_clip(payload.story, 8000) or "（未提供）"}

# 外部剧本
{_clip(payload.script, 8000) or "（未提供）"}

# 外部分镜剧本
{_clip(payload.storyboard_script, 8000) or "（未提供）"}

# 外部图片
{f"已随请求附加 {len(payload.images)} 张图片，请结合图片内容校验视觉信息。" if payload.images else "（未提供）"}
"""


class MetadataImportAgent(ImportLayerAgent):
    layer_id = "work_metadata"
    agent_name = "作品元数据导入智能体"
    role_id = "制片人"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        imported_at = datetime.now().strftime(memory_manager.TIME_FORMAT)
        raw_keys = (
            ", ".join(sorted(payload.raw_payload.keys()))
            if payload.raw_payload
            else "无"
        )
        content = f"""# 作品元数据

作品名称：{payload.work_name}
来源系统：{payload.source_system}
来源workid：{payload.external_work_id}
来源URL：{payload.source_url or "未提供"}
导入时间：{imported_at}
导入方式：外部项目读取原始内容后调用 pm-mem 导入协作接口
内容类型：漫画/短剧改编素材
原始字段：{raw_keys}

## 导入说明

本作品由导入协作接口生成分层记忆草稿。用户可在 Web 管理页审核、修订和锁定各层内容。
"""
        return self._draft(content)


class CoreSettingImportAgent(ImportLayerAgent):
    layer_id = "core_setting"
    agent_name = "核心设定整理智能体"
    role_id = "制片人"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        content = "\n\n".join(
            [
                "# 核心设定层",
                self._section("从故事提取的稳定设定", payload.story, "故事"),
                self._section("从剧本提取的设定线索", _clip(payload.script), "剧本"),
                self._section(
                    "从分镜提取的视觉/场景约束",
                    _clip(payload.storyboard_script),
                    "分镜剧本",
                ),
                "## 待审核事项\n\n- 请人工确认题材、职场背景、核心冲突、人物关系和不可改写设定。\n- 审核后建议锁定本层，作为后续创作一致性的最高约束。",
            ]
        )
        return self._draft(content)


class CharacterProfileImportAgent(ImportLayerAgent):
    layer_id = "character_profile"
    agent_name = "人物档案整理智能体"
    role_id = "编剧"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        content = "\n\n".join(
            [
                "# 人物档案层",
                "## 人物原始线索",
                _join_source_blocks(
                    [
                        ("故事", payload.story),
                        ("剧本", payload.script),
                    ],
                    empty="（暂无可解析人物线索，待人工补充角色姓名、岗位、关系、口吻和动机。）",
                ),
                "## 待审核事项\n\n- 请从原始线索中整理每个角色的姓名、岗位、性格、目标、关系和口吻。\n- 后续 AI 创作应优先遵守本层的人物口吻和行为边界。",
            ]
        )
        return self._draft(content)


class PlotContextImportAgent(ImportLayerAgent):
    layer_id = "plot_context"
    agent_name = "情节脉络整理智能体"
    role_id = "编剧"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        content = "\n\n".join(
            [
                "# 情节脉络层",
                self._section("故事脉络", payload.story, "故事"),
                self._section("剧本事件线", _clip(payload.script, 6000), "剧本"),
                "## 待审核事项\n\n- 请人工确认第一集起点、关键冲突、转折、结尾钩子和时间线。\n- 如果故事与剧本存在冲突，以审核后的本层内容为准。",
            ]
        )
        return self._draft(content)


class ScriptArchiveImportAgent(ImportLayerAgent):
    layer_id = "script_archive"
    agent_name = "剧本档案归档智能体"
    role_id = "编剧"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        content = "\n\n".join(
            [
                "# 剧本档案层",
                self._section("外部剧本原文", payload.script, "剧本"),
                self._section("可参考故事原文", payload.story, "故事"),
            ]
        )
        return self._draft(content)


class StoryboardArchiveImportAgent(ImportLayerAgent):
    layer_id = "storyboard_archive"
    agent_name = "分镜档案归档智能体"
    role_id = "分镜师"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        content = "\n\n".join(
            [
                "# 分镜档案层",
                self._section(
                    "外部分镜剧本原文",
                    payload.storyboard_script,
                    "分镜剧本",
                ),
                self._section("剧本视觉参考", _clip(payload.script), "剧本"),
            ]
        )
        return self._draft(content)


class ConsistencyReviewImportAgent(ImportLayerAgent):
    layer_id = "import_review"
    agent_name = "导入一致性校验智能体"
    role_id = "一致性校验员"

    def build(
        self,
        payload: ExternalWorkPayload,
        drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        notes = []
        if not payload.story.strip():
            notes.append("未提供 story 字段。")
        if not payload.script.strip():
            notes.append("未提供 script 字段。")
        if not payload.storyboard_script.strip():
            notes.append("未提供 storyboard_script 字段。")
        if not notes:
            notes.append("故事、剧本、分镜剧本均已提供。")

        content = "# 导入校验\n\n" + "\n".join(f"- {note}" for note in notes)
        return self._draft(content, notes=notes)


class ExternalWorkImportCoordinator:
    """Coordinate layer agents and write their drafts to Markdown memory."""

    def __init__(
        self,
        operator: str = "导入协作智能体",
        llm_client: Optional[LocalResponsesLLMClient] = None,
        backup_llm_client: Optional[DeepSeekChatLLMClient] = None,
        llm_settings: Optional[ImportLLMSettings] = None,
    ):
        self.operator = operator
        self.llm_settings = llm_settings or load_import_llm_settings()
        self.llm_client = llm_client
        if self.llm_client is None:
            self.llm_client = LocalResponsesLLMClient(self.llm_settings)
        self.backup_llm_client = backup_llm_client
        self.layer_agents: List[ImportLayerAgent] = [
            MetadataImportAgent(),
            CoreSettingImportAgent(),
            CharacterProfileImportAgent(),
            PlotContextImportAgent(),
            ScriptArchiveImportAgent(),
            StoryboardArchiveImportAgent(),
        ]
        self.review_agent = ConsistencyReviewImportAgent()

    def import_work(
        self,
        payload: ExternalWorkPayload,
        dry_run: bool = False,
    ) -> Dict[str, Any]:
        existing_work_id = find_existing_imported_work(
            payload.source_system,
            payload.external_work_id,
        )
        work_id = existing_work_id
        created = False
        if work_id is None and not dry_run:
            work_id = memory_manager.create_work(payload.work_name)
            created = True

        drafts: Dict[str, LayerDraft] = {}
        for agent in self.layer_agents:
            draft = agent.build(payload, drafts)
            draft = self._process_draft_with_role_llm(
                agent,
                payload,
                draft,
                drafts,
            )
            drafts[draft.layer_id] = draft

        review = self.review_agent.build(payload, drafts)
        remem_tasks: Dict[str, Dict[str, Any]] = {}
        if not dry_run and work_id is not None:
            for draft in drafts.values():
                remem_tasks[draft.layer_id] = self._write_draft_via_remem(
                    work_id=work_id,
                    payload=payload,
                    draft=draft,
                )

        return {
            "success": True,
            "dry_run": dry_run,
            "created": created,
            "work_id": work_id,
            "existing_work_id": existing_work_id,
            "work_name": payload.work_name,
            "source_system": payload.source_system,
            "external_work_id": payload.external_work_id,
            "layers": {
                layer_id: {
                    "agent_name": draft.agent_name,
                    "role_id": draft.role_id,
                    "role_name": draft.role_name,
                    "role_file": draft.role_file,
                    "role_prompt": draft.role_prompt,
                    "role_prompt_hash": draft.role_prompt_hash,
                    "llm_provider": draft.llm_provider,
                    "llm_processed": draft.llm_processed,
                    "llm_model": draft.llm_model,
                    "llm_endpoint": draft.llm_endpoint,
                    "llm_primary_error": draft.llm_primary_error,
                    "llm_error": draft.llm_error,
                    "content": draft.content,
                    "notes": draft.notes,
                }
                for layer_id, draft in drafts.items()
            },
            "review": {
                "agent_name": review.agent_name,
                "content": review.content,
                "notes": review.notes,
            },
            "remem_tasks": remem_tasks,
            "web_url": f"/work/{work_id}" if work_id else None,
        }

    def _write_draft_via_remem(
        self,
        work_id: str,
        payload: ExternalWorkPayload,
        draft: LayerDraft,
    ) -> Dict[str, Any]:
        role = RoleFactory.create(draft.role_id)
        task_input = (
            f"导入外部作品《{payload.work_name}》的 {draft.layer_id} 层记忆。"
            "请检索已有记忆，合并新增事实，锁定或冲突内容应标记而不是覆盖。\n\n"
            f"{draft.content}"
        )
        context = TaskContext(
            task_type="external_work_import",
            source="external_work_import_coordinator",
            role_id=role.role_id,
            metadata={
                "work_id": work_id,
                "target_layers": [draft.layer_id],
                "source_system": payload.source_system,
                "external_work_id": payload.external_work_id,
                "source_url": payload.source_url,
                "llm_provider": draft.llm_provider,
                "llm_model": draft.llm_model,
                "layer_metadata": _draft_metadata(payload, draft),
            },
        )
        agent = ReMemAgent(
            llm=_SingleActLLM(draft.content),
            memory_store=MarkdownLayerMemoryStore(),
            trace_store=MarkdownTraceStore(),
            max_iterations=1,
            retrieval_k=6,
        )
        result = agent.run_task(task_input, role=role, context=context)
        return {
            "task_id": result.get("task_id"),
            "status": result.get("status"),
            "memory_updated": result.get("memory_updated", False),
            "applied_operations": result.get("applied_operations", []),
            "conflicts": result.get("conflicts", []),
        }

    def _process_draft_with_role_llm(
        self,
        agent: ImportLayerAgent,
        payload: ExternalWorkPayload,
        draft: LayerDraft,
        previous_drafts: Dict[str, LayerDraft],
    ) -> LayerDraft:
        role = role_manager.get_role_config(draft.role_id)
        if role:
            draft.role_name = role["role_name"]
            draft.role_file = role["role_file"]
            draft.role_prompt = role["prompt"]
            draft.role_prompt_hash = role["prompt_hash"]

        draft.llm_provider = "local_proxy_responses"
        draft.llm_model = self.llm_settings.model
        draft.llm_endpoint = self.llm_settings.endpoint
        if self.llm_client is None:
            self.llm_client = LocalResponsesLLMClient(self.llm_settings)

        prompt = agent.build_llm_prompt(payload, draft, draft.role_prompt, previous_drafts)
        prompt = _clip_middle(prompt, self.llm_settings.max_prompt_chars)
        primary_error = ""
        try:
            refined = self.llm_client.generate(prompt, images=payload.images)
            refined = _clean_llm_markdown(refined)
            if refined:
                draft.content = refined
                draft.llm_processed = True
                return draft
            primary_error = "local proxy LLM returned empty content"
        except Exception as exc:
            primary_error = _clip(str(exc), 1000)

        draft.llm_primary_error = primary_error
        backup_error = self._try_deepseek_backup(prompt, payload, draft)
        if backup_error:
            draft.llm_error = _clip(
                f"local_proxy_responses: {primary_error}\n"
                f"deepseek_backup: {backup_error}",
                1200,
            )
            if not self.llm_settings.fallback_to_deterministic:
                raise RuntimeError(draft.llm_error)
        return draft

    def _try_deepseek_backup(
        self,
        prompt: str,
        payload: ExternalWorkPayload,
        draft: LayerDraft,
    ) -> str:
        backup_settings = self.llm_settings.deepseek_backup
        if self.backup_llm_client is None:
            self.backup_llm_client = DeepSeekChatLLMClient(backup_settings)

        try:
            refined = self.backup_llm_client.generate(prompt, images=payload.images)
            refined = _clean_llm_markdown(refined)
            if not refined:
                return "DeepSeek returned empty content"
            draft.content = refined
            draft.llm_provider = "deepseek_backup"
            draft.llm_model = backup_settings.model
            draft.llm_endpoint = backup_settings.endpoint
            draft.llm_processed = True
            draft.llm_error = ""
            return ""
        except Exception as exc:
            return _clip(str(exc), 1000)


class _SingleActLLM:
    """Small deterministic adapter used to route prepared import drafts via ReMem."""

    def __init__(self, action_output: str):
        self.action_output = action_output

    def __call__(self, prompt: str) -> str:
        if "请选择下一步动作" in prompt or "请选择动作" in prompt:
            return "act"
        return f"Act: {self.action_output}"

    def get_model_info(self) -> Dict[str, Any]:
        return {"model": "deterministic-import-act", "context_length_tokens": 64000}


def build_external_work_payload(
    external_work_id: str,
    work_name: str,
    source_system: str = DEFAULT_SOURCE_SYSTEM,
    source_url: str = "",
    story: str = "",
    script: str = "",
    storyboard_script: str = "",
    images: Optional[List[str]] = None,
    raw_payload: Optional[Dict[str, Any]] = None,
) -> ExternalWorkPayload:
    return ExternalWorkPayload(
        source_system=(source_system or DEFAULT_SOURCE_SYSTEM).strip(),
        external_work_id=str(external_work_id).strip(),
        work_name=work_name.strip(),
        source_url=source_url.strip(),
        story=story or "",
        script=script or "",
        storyboard_script=storyboard_script or "",
        images=images or [],
        raw_payload=raw_payload or {},
    )


def find_existing_imported_work(source_system: str, external_work_id: str) -> Optional[str]:
    source_markers = [
        f"来源系统：{source_system}",
        f"来源系统:{source_system}",
        f"source_system: {source_system}",
    ]
    id_markers = [
        f"来源workid：{external_work_id}",
        f"来源workid:{external_work_id}",
        f"external_work_id: {external_work_id}",
    ]

    for work in memory_manager.list_works():
        work_id = work["work_id"]
        try:
            metadata = memory_manager.get_layer_content(work_id, "work_metadata")
        except Exception:
            continue
        front_matter = metadata.get("metadata", {})
        if (
            str(front_matter.get("source_system", "")).strip() == source_system
            and str(front_matter.get("external_work_id", "")).strip()
            == str(external_work_id)
        ):
            return work_id
        content = metadata.get("content", "")
        if any(marker in content for marker in source_markers) and any(
            marker in content for marker in id_markers
        ):
            return work_id
    return None


def _draft_metadata(payload: ExternalWorkPayload, draft: LayerDraft) -> Dict[str, Any]:
    return {
        "import_agent_name": draft.agent_name,
        "processed_by_role_id": draft.role_id,
        "processed_by_role_name": draft.role_name,
        "role_prompt_file": draft.role_file,
        "role_prompt_hash": draft.role_prompt_hash,
        "llm_provider": draft.llm_provider,
        "llm_processed": draft.llm_processed,
        "llm_model": draft.llm_model,
        "llm_endpoint": draft.llm_endpoint,
        "llm_primary_error": draft.llm_primary_error,
        "llm_error": draft.llm_error,
        "source_system": payload.source_system,
        "external_work_id": payload.external_work_id,
    }


def _clip(text: str, max_chars: int = 3000) -> str:
    normalized = (text or "").strip()
    if len(normalized) <= max_chars:
        return normalized
    return normalized[:max_chars].rstrip() + "\n\n（内容过长，已截取前段；完整内容请查看对应归档层。）"


def _clip_middle(text: str, max_chars: int) -> str:
    if max_chars <= 0 or len(text) <= max_chars:
        return text
    keep_head = max_chars // 2
    keep_tail = max_chars - keep_head
    return (
        text[:keep_head].rstrip()
        + "\n\n（中间内容因提示词长度限制已省略）\n\n"
        + text[-keep_tail:].lstrip()
    )


def _clean_llm_markdown(text: str) -> str:
    stripped = (text or "").strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        stripped = "\n".join(lines).strip()
    return stripped


def _summarize_previous_drafts(drafts: Dict[str, LayerDraft]) -> str:
    parts = []
    for draft in drafts.values():
        layer_name = memory_manager.get_layer_definition(draft.layer_id)["layer_name"]
        parts.append(f"## {layer_name}\n{_clip(draft.content, 1200)}")
    return "\n\n".join(parts)


def _join_source_blocks(blocks: List[tuple], empty: str) -> str:
    parts = []
    for title, content in blocks:
        if content and content.strip():
            parts.append(f"### {title}\n\n{content.strip()}")
    return "\n\n".join(parts) if parts else empty
