work_id: 70c35205-9106-4dce-a263-0122064db69a
work_name: Plus封号潮的背后故事
create_time: '2026-05-01 21:30:55'
update_time: '2026-05-02 21:30:54'
status: active
layer_lock_status:
  01_作品元数据层: false
  02_核心设定层: false
  03_人物档案层: false
  04_情节脉络层: false
  05_剧本档案层: false
  06_分镜档案层: false
