work_id: a5e41eda-a934-4a99-9544-bd6f5dad5f4a
work_name: 职场见闻第一集
create_time: '2026-04-30 07:25:32'
update_time: '2026-04-30 09:54:23'
status: active
layer_lock_status:
  01_作品元数据层: false
  02_核心设定层: false
  03_人物档案层: false
  04_情节脉络层: false
  05_剧本档案层: false
  06_分镜档案层: false
